# Lambda Layers for Gorggle
# This file manages Lambda layers for external dependencies
# ARNs are auto-generated by scripts/package_lambda_layers.sh

# Variables for layer ARNs (set via layer_arns.auto.tfvars)
variable "ffmpeg_layer_arn" {
  type        = string
  description = "ARN of the FFmpeg Lambda layer (created by package_lambda_layers.sh)"
  default     = ""
}

variable "requests_layer_arn" {
  type        = string
  description = "ARN of the requests library Lambda layer (created by package_lambda_layers.sh)"
  default     = ""
}

# If layers are provided, attach them to relevant Lambda functions
locals {
  # Functions that need FFmpeg
  ffmpeg_functions = var.ffmpeg_layer_arn != "" ? [var.ffmpeg_layer_arn] : []
  
  # Functions that need requests library
  requests_functions = var.requests_layer_arn != "" ? [var.requests_layer_arn] : []
}

# Note: Layer attachments are handled in main.tf via the layers parameter
# This file just defines the variables and validation
